language: php
php:
  - '5.5'
  - '5.4'
  - '7.0'
  - 'hhvm'
before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -v

after_script:
  - php vendor/bin/coveralls -v
